export const dropdownOptionsMap = {
  positions: ['top', 'bottom', 'left', 'right'],
  displayTypes: ['comma', 'chip'],
  appearances: ['basic', 'text', 'outlined', 'link'],
  buttonLayouts: ['stacked', 'horizontal', 'vertical'],
  keyFilters: [/.*/g, 'pint', 'int', 'pnum', 'num', 'hex', 'email', 'alpha', 'alphanum'],
  currencies: ['USD', 'EUR', 'IRR'],
  currencyDisplays: ['symbol', 'code', 'name'],
  labelPositions: ['float', 'side', 'top'],
  orientations: ['horizontal', 'vertical'],
  dropdownModes: ['blank', 'current'],
  severities: ['primary', 'secondary', 'success', 'info', 'warning', 'danger', 'help', 'contrast'],
  hourFormats: ['12', '24'],
  views: ['date', 'month', 'year'],
  statuses: ['none', 'success', 'info', 'warning', 'error', '403', '404', '500'],
  imageTypes: ['none', 'box1', 'box2', 'magnifier'],
  iconDisplayTypes: ['input', 'button'],
  addon: ['none', 'iconRight', 'iconLeft', 'addonStart', 'addonEnd', 'addonBoth'],
  sizes: ['none', 'small', 'large'],
  colorFormats: ['hex', 'rgb', 'hsb'],
  modes: ['basic', 'advanced'],
  selectionModes: ['none', 'single', 'multiple', 'checkbox'],
  datepickerSelectionModes: ['single', 'multiple', 'range'],
  numberModes: ['decimal', 'currency'],
  fixLabelPositions: ['side', 'top'],
  defaultFocusTypes: ['none', 'accept', 'reject', 'close'],
  toastPositions: ['top-right', 'top-left', 'bottom-right', 'bottom-left', 'top-center', 'bottom-center', 'center'],
  toastSeverities: ['secondary', 'success', 'info', 'warn', 'error', 'contrast'],
  dialogPositions: ['top', 'bottom', 'left', 'right', 'top-left', 'top-right', 'bottom-left', 'bottom-right', 'center'],
  pinchLimitZoomLevels: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 20, 30, 40, 'original image size'],
  pinchOverflows: ['hidden', 'visible'],
  pinchDisableZoomControls: ['disable', 'never', 'auto'],
  pinchListeners: ['auto', 'mouse and touch'],
  variants: ['outlined', 'filled']
};
